project:
  type: website
  output-dir: docs

website:
  title: "Mod"
  favicon: download.png
  navbar:
    background: "black"
    search: true
    left:
      -  text: "Accueil"
         href: index.qmd
      -  text: "Métadonnées"
         href: metadata.qmd
      -  text: "Données Brutes"
         href: data.qmd
      -  text: "Données en Log"
         href: logdata.qmd
      -  text: "Modèle IT"
         href: IT_modele.qmd
      -  text: "Modèle ET"
         href: ET_modele.qmd
      - text: "Tests fondamentaux"
        menu:
          - text: "Test de Normalité des variables"
            href: jacquesbera.qmd
          - text: "Tests de Stationnarité"
            href: stationarity.qmd
          - text: "Le nombre de retard Maximal"
            href: maxlag.qmd
          - text: "Test de Cointégration"
            href: cointegration_test.qmd
      - text: "Validation des Modeles"
        menu:
          - text: "Les Tests Diagnostic"
            href: diagnostic_tests.qmd
          - text: "Test CUSUM"
            href: cusum_test.qmd
      - text: "Test Economique"
        menu:
          - text: "test de Normalite des series d'interet"
            href: normality_test.qmd
          - text: "Corrélation de Kendall"
            href: kendall_correlation.qmd
          - text: "Causalité de Granger"
            href: granger_causality.qmd 
      - text: "Cadre Operatoire"
        href: cadre_operatoire.qmd     
execute:
  echo: false
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true